file:
  upload:
    path: C:\file1
logging:
  level:
    com:
      example: DEBUG
    org:
      springframework: INFO
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8080
  servlet:
    context-path: /douyin
spring:
  profiles:
    #    active: release
    active: dev
  mvc:
    path:
      match:
        matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 2000MB
      max-request-size: 20000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 250088
    url: jdbc:mysql://localhost:3306/tiktok?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  redis:
    channel:
      msgToAll: websocket.msgToAll
      userStatus: websocket.userStatus
    set:
      onlineUsers: websocket.onlineUsers
    host: 127.0.0.1
    port: 6379
    database:
      db0: 0
      db1: 1
    timeout: 3000
    pool:
      max-active: 100
      max-idle: 3
      min-idle: 0
      max-wait: -1
    password:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    listener:
      simple:
        concurrency: 2
        max-concurrency: 4
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
          multiplier: 2
          initial-interval: 3000
          max-interval: 16000
swagger:
  enabled: true